FROM rust:1.88.0-bullseye AS builder
RUN apt-get update && apt-get -y upgrade && apt-get install -y cmake libclang-dev
WORKDIR /lighthouse
COPY . .
RUN cargo build --release --bin lighthouse

FROM ubuntu:22.04
RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
  libssl-dev \
  ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
COPY --from=builder /lighthouse/target/release/lighthouse /usr/local/bin/lighthouse
ENTRYPOINT ["lighthouse"]
